version: "3"
services:
  network:
    image: openmined/grid-network:production
    environment:
      - PORT=7000
      - SECRET_KEY=ineedtoputasecrethere
      - DATABASE_URL=sqlite:///databasenetwork.db
    ports:
      - 7000:7000
  alice:
    image: openmined/grid-node:production
    environment:
      - NODE_ID=Alice
      - ADDRESS=http://alice:5000/
      - PORT=5000
      - NETWORK=http://network:7000
      - DATABASE_URL=sqlite:///databasenode.db
    depends_on:
      - 'network'
    ports:
      - 5000:5000

  bob:
    image: openmined/grid-node:production
    environment:
      - NODE_ID=Bob
      - ADDRESS=http://bob:5001/
      - PORT=5001
      - NETWORK=http://network:7000
      - DATABASE_URL=sqlite:///databasenode.db
    depends_on:
      - 'network'
    ports:
      - 5001:5001

  charlie:
    image: openmined/grid-node:production
    environment:
      - NODE_ID=Charlie
      - ADDRESS=http://charlie:5002/
      - PORT=5002
      - NETWORK=http://network:7000
      - DATABASE_URL=sqlite:///databasenode.db
    depends_on:
      - 'network'
    ports:
      - 5002:5002
  notebooks:
    depends_on:
      - 'charlie'
    build:
      context: .
      dockerfile: Notebooks.Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks/results:/src/results
